"""
Payment reminder Celery tasks.

Strategy (per spec):
  1. Always attempt email first (core channel)
  2. Only additionally attempt WhatsApp if company.whatsapp_addon_enabled is True
     WhatsApp is never a substitute for email — only an addition.

Reminder text is generated by Claude to read like a polite human message,
not a robotic dunning notice (validated pain point: owners find it psychologically
uncomfortable to personally chase customers for payment).
"""
from celery_app import celery
from app.extensions import db
from app.models.pdc import PDC
from app.models.company import Company


@celery.task
def send_pdc_reminders():
    """Scan PDCs in pending_deposit state and send reminders near cheque_date."""
    from datetime import date, timedelta
    from flask import current_app

    today = date.today()
    window_days = 3  # remind 3 days before cheque_date

    due_pdcs = (
        db.session.query(PDC)
        .filter(PDC.pdc_status == "pending_deposit")
        .filter(PDC.cheque_date <= today + timedelta(days=window_days))
        .filter(PDC.cheque_date >= today)
        .all()
    )

    for pdc in due_pdcs:
        company = db.session.get(Company, pdc.company_id)
        if company is None:
            continue
        _dispatch_reminder(pdc, company)


def _dispatch_reminder(pdc: PDC, company: Company):
    from app.services.email_service import send_email, EmailError
    from app.services.whatsapp_service import send_whatsapp, WhatsAppError

    subject, html, text = _generate_reminder_text(pdc, company)

    # Core channel — email always attempted
    if pdc.customer and pdc.customer.email:
        try:
            send_email(pdc.customer.email, subject, html, text)
        except EmailError as exc:
            import logging
            logging.getLogger(__name__).error("Email reminder failed for PDC %s: %s", pdc.id, exc)

    # Add-on channel — WhatsApp only if enabled and customer has a number
    if company.whatsapp_addon_enabled and pdc.customer and pdc.customer.whatsapp_number:
        try:
            send_whatsapp(company, pdc.customer.whatsapp_number, text)
        except WhatsAppError as exc:
            import logging
            logging.getLogger(__name__).error("WhatsApp reminder failed for PDC %s: %s", pdc.id, exc)


def _generate_reminder_text(pdc: PDC, company: Company) -> tuple[str, str, str]:
    """
    Use Claude to write a polite, natural-sounding reminder.
    Falls back to a template if the Claude call fails.
    """
    try:
        return _claude_reminder(pdc, company)
    except Exception:
        return _template_reminder(pdc, company)


def _claude_reminder(pdc: PDC, company: Company) -> tuple[str, str, str]:
    import anthropic
    from flask import current_app

    api_key = current_app.config.get("ANTHROPIC_API_KEY", "")
    model = current_app.config.get("EXTRACTION_MODEL", "claude-opus-4-5-20251101")
    client = anthropic.Anthropic(api_key=api_key)

    prompt = (
        f"Write a polite, warm payment reminder from {company.name} to their customer "
        f"regarding a post-dated cheque of {pdc.currency} {float(pdc.amount):,.2f} "
        f"due on {pdc.cheque_date}. Cheque #{pdc.cheque_number}, bank: {pdc.bank_name}. "
        f"The reminder should sound like a caring colleague, not a debt collector. "
        f"Keep it under 80 words. Return only the message body — no subject line, no greeting prefix."
    )

    resp = client.messages.create(
        model=model,
        max_tokens=256,
        messages=[{"role": "user", "content": prompt}],
    )
    body = resp.content[0].text.strip()
    subject = f"Payment Reminder — {pdc.currency} {float(pdc.amount):,.2f} due {pdc.cheque_date}"
    html = f"<p>{body}</p>"
    return subject, html, body


def _template_reminder(pdc: PDC, company: Company) -> tuple[str, str, str]:
    amount_str = f"{pdc.currency} {float(pdc.amount):,.2f}"
    text = (
        f"Dear valued customer, this is a friendly reminder from {company.name} "
        f"that a cheque of {amount_str} (#{pdc.cheque_number}) is due on {pdc.cheque_date}. "
        f"Please ensure it clears on time. Thank you."
    )
    subject = f"Payment Reminder — {amount_str} due {pdc.cheque_date}"
    html = f"<p>{text}</p>"
    return subject, html, text
